<testsuite name="login.login on chrome" tests="3" errors="1" failures="1" skipped="0" time="11.917868" timestamp="2024-03-25T20:50:46.446370" hostname="manticminotaur"><testcase classname="login.login on chrome" name="Login with correct credentials" status="failed" time="9.04901"><failure type="AssertionError" message="Login was not successful">
<![CDATA[
Failing step: Then I should be logged in successfully ... failed in 0.000s
Location: tests/login.feature:10
Assertion Failed: Login was not successful
Captured logging:
ERROR:scripts.script_login:Timeout occurred while waiting for element]]>
</failure><system-out>
<![CDATA[
@scenario.begin

  @positive-case, @must-passed, @login
  Scenario: Login with correct credentials
    Given I open the chrome browser ... passed in 3.172s
    Given I open the login page ... passed in 0.675s
    When I enter the correct username "hongducdev" and password "123456" ... passed in 5.202s
    Then I should be logged in successfully ... failed in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.login on chrome" name="Login with incorrect password" status="failed" time="2.868858"><error type="KeyboardInterrupt" message="">
<![CDATA[
Failing step: When I enter the correct username "hongducdev" and incorrect password "incorrectpassword" ... failed in 1.012s
Location: tests/login.feature:15
ABORTED: By user (KeyboardInterrupt).
Captured logging:
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /session/e1965e1fb7bb1ddca38be1dd893060a1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7031227490d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e1965e1fb7bb1ddca38be1dd893060a1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x703122749510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e1965e1fb7bb1ddca38be1dd893060a1]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @negative-case, @must-passed, @login
  Scenario: Login with incorrect password
    Given I open the chrome browser ... passed in 1.292s
    Given I open the login page ... passed in 0.565s
    When I enter the correct username "hongducdev" and incorrect password "incorrectpassword" ... failed in 1.012s
    Then I should not be logged in ... skipped in 0.000s
    And I should see the message "Incorrect password" ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.login on chrome" name="Login with nonexistent username" status="untested" time="0"><system-out>
<![CDATA[
@scenario.begin

  @negative-case, @login
  Scenario: Login with nonexistent username
    Given I open the chrome browser ... untested in 0.000s
    Given I open the login page ... untested in 0.000s
    When I enter a nonexistent username "nonexistentusername" and password "123456" ... untested in 0.000s
    Then I should not be logged in ... untested in 0.000s
    And I should see the message "Nonexistent username" ... untested in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>